### ISSUE TITLE
Consider making `to_object()` synonymous to `from_items()` functions for compatibility across libraries.

### ISSUE THREAD

**Issue by springcomp** [jmespath-unofficial/jmespath.jep#11]

**Comment by springcomp** [comment]
Rationale: 
- https://github.com/jmespath/jmespath.jep/issues/20
- https://github.com/jmespath/jmespath.py/pull/105#issuecomment-204719940

**Comment by innovate-invent** [comment]
Can I move this to a discussion?

**Comment by springcomp** [comment]
Sure. Please do.
