### ISSUE TITLE
Empty quoted string should be allowed

### ISSUE THREAD

**Issue by gibson042** [jmespath-unofficial/jmespath.jep#127]
The `quoted-string` rule currently requires at least one character between the quotation marks (<code> quoted-string     = quote <strong>1*</strong>(unescaped-char / escaped-char) quote</code>), but it should not because JSON object members can be named like `""`. For example, an expression like ``` `{"": "foo"}` | ""``` should be valid and result in `"foo"` (as is in fact already the case in the live demo at the top of https://jmespath.site/ ).

**Comment by springcomp** [comment]
TIL that empty names are indeed valid JSON keys 😲 !
