### ISSUE TITLE
Why is `{` left-brace character omitted from the `unescaped-literal` rule?

### ISSUE THREAD

**Issue by springcomp** [jmespath-unofficial/jmespath.jep#135]
The `unescaped-literal` rule is one possibility to express the contents of a JSON string literal.
The grammar currently considers this syntax invalid:

`` `"{"` ``

Is this an error?

**Comment by gibson042** [comment]
Where are you seeing that? `unescaped-literal` was renamed to `json-unescaped` in ad2412afed83da91b2b5368a40aa727d2d2cc7e3, but AFAICT does not exclude U+007B LEFT CURLY BRACKET either before or after those changes (although the former did have an unnecessary `%x61-7A / %x7B-10FFFF` range break).

**Comment by springcomp** [comment]
I could see that in [the original spec](https://jmespath.site/#specification).

All is 👍 it is indeed fixed [in the preview](https://jmespath.site/main#specification).
