### ISSUE TITLE
JMESPath vNext

### ISSUE THREAD

**Issue by springcomp** [jmespath-unofficial/jmespath.jep#14]
This issue tracks the progress towards the next iteration of the JMESPath specification.
These are the planned current issues and proposals included in the next version.

- #13

**Comment by innovate-invent** [comment]
Should we close this in lieu of the matching discussion?

**Comment by springcomp** [comment]
Why not. We will create appropriate issues  when we have decided on the milestone.

**Comment by innovate-invent** [comment]
Yea, the JEP PRs should be attached to milestones, rather than issues.

**Comment by springcomp** [comment]
> Yea, the JEP PRs should be attached to milestones, rather than issues.

How do you scope beforehand a milestone?
I thought you would select a subset of issues to form a milestone and track progress by issuing PRs that get accepted and merged?

**Comment by innovate-invent** [comment]
I guess I assumed the PR would happen very early in the process, with the associated branch being stubbed and developed.
