### ISSUE TITLE
Link to https://jmespath.site/specification.html broken (?)

### ISSUE THREAD

**Issue by sebastien-rosset** [jmespath-unofficial/jmespath.jep#160]
The [README.md](https://github.com/jmespath-community/jmespath.spec/blame/main/README.md#L6) file has a link to https://jmespath.site/specification.html, and currently this link is broken. I'm not sure if it's a temporary issue or not.
That links returns "We are sorry, but that page could not be found."

> Any changes to the JMESPath specification (https://jmespath.site/specification.html) must have a JEP (JMESPath 

It would help to include a link to the source for the spec, not just the generated html page. Or maybe it's already there in the HTML page, but since the link is broken, I cannot see it right now.

**Comment by sebastien-rosset** [comment]
Thanks for the quick fix. I should have mentioned the same link is provided twice in the README.md file:

> Any functionality change that would require an update to the specification (http://jmespath.site/specification.html) requires a JEP.

**Comment by springcomp** [comment]
Thank you very much.

I will definitely spend more time on the branding and documentation when the project is sufficiently kicked off. Hopefully soon ish.
