### ISSUE TITLE
[styling] Consider supporting styling for function arguments and results differently than plain text

### ISSUE THREAD

**Issue by springcomp** [jmespath-unofficial/jmespath.jep#63]
This is part of a [series or minor issues](/jmespath-community/jmespath.spec/labels/css-styling) that aim to enable support for flexible styling and theming of the JMESPath site.

![image](https://user-images.githubusercontent.com/8488398/164182630-00642514-9d5a-4343-abb8-864a77ed93e0.png)

The table cells that illustrate function usage all share the same `td` HTML tag.
Please, consider adding a CSS-class to allow to format the cells from the `Given`, `Expression` and `Result` columns differently than those from the `Presence` and `Description` columns.

**Comment by innovate-invent** [comment]
is the following acceptable?
```scss
#functions {
  table.args {
    td:nth-of-type(1) {} // Name
    td:nth-of-type(2) {} // Presence
    td:nth-of-type(3) {} // Type
    td:nth-of-type(4) {} // Description
  }

  table.examples {
    td:nth-of-type(1) {} // Given
    td:nth-of-type(2) {} // Expression
    td:nth-of-type(3) {} // Result
  }
}
```

**Comment by springcomp** [comment]
I guess this will work. Thanks for the feedback.
